services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    networks:
      - cassandra-elk-network
    volumes:
      - ./scripts:/scripts

networks:
  cassandra-elk-network:
    name: cassandra-elk-network