services:
  cassandra:
    build: .
    container_name: cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    networks:
      - cassandra-elk-network
    volumes:
      - ./scripts:/scripts

networks:
  cassandra-elk-network:
    name: cassandra-elk-network