services:
  cassandra:
    build: .
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    networks:
      - pensieve-network
    volumes:
      - ./scripts:/scripts

networks:
  pensieve-network:
    name: pensieve-network