services:
  logstash:
    build: .
    container_name: logstash
    volumes:
      - ../../certs:/usr/share/logstash/config/certs
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5044:5044"
    networks:
      - pensieve-network

networks:
  pensieve-network:
    name: pensieve-network