services:
  logstash:
    build: .
    container_name: logstash
    volumes:
      - ../../certs:/usr/share/logstash/config/certs
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
    networks:
      - cassandra-elk-network

networks:
  cassandra-elk-network:
    name: cassandra-elk-network