services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=SHfU_X+RpYkpddZzynxN
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - cassandra-elk-network

  #  kibana:
  #    image: kibana:8.13.0
  #    container_name: kibana
  #    ports:
  #      - "5601:5601"
  #    environment:
  #      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #    depends_on:
  #      - elasticsearch

networks:
  cassandra-elk-network:
    name: cassandra-elk-network